server:
  port: 8081
spring:
  application:
    name: tmp

  datasource:
    url: jdbc:mysql://localhost:3306/task_management_platform?characterEncoding=utf8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
# Specify the DBMS
  jpa:
   database: MYSQL
# Show or not log for each sql query
   show-sql: true
# Hibernate ddl auto (create, create-drop, update)
   hibernate:
      ddl-auto: update
      name-strategy: org.hibernate.cfg.improvedNamingStrategy
# Naming strategy
# stripped before adding them to the entity manager)
   properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
          use_query_cache: false
#logging:level:root: debug